<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RequestFlow;
use Carbon\Carbon;
class RequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        foreach (range(1,10) as $index) {
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'status' => 'new',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'status' => 'submitted-for-review',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Im not paying You',
                'status' => 'finance-rejected',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Im not paying You',
                'status' => 'manager-rejected',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Im not paying You',
                'status' => 'director-rejected',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Im not paying You',
                'status' => 'rejected',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Good Luck',
                'status' => 'finance-ok',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Out of my budget',
                'status' => 'threshold-exceeded',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Have Fun',
                'status' => 'manager-confirmed',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Have Fun',
                'status' => 'director-confirmed',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Depends on my mood',
                'status' => 'confirmed-partially',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
            RequestFlow::create([
                'initiator' => 'user',
                'company_id' => '1',
                'department_id' => '1',
                'supplier_id' => '1',
                'expense_type_id' => '1',
                'currency' => 'USD',
                'amount' => '45',
                'amount_in_gel' => '10.09',
                'description' => 'I am testing',
                'basis' => '168164621911.png',
                'payment_date' => '2023-04-19',
                'submission_date' => '2023-05-19',
                'comment' => 'Ok',
                'status' => 'paid',
                'user_id' => '3',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]);
        }
    }
}
